name: dotnet

on:
  push:
    branches:
      - '**'

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          ACCEPT_EULA: Y
          MSSQL_SA_PASSWORD: SomethingSuperSecret!123
          MSSQL_PID: Developer
        ports:
          - 1433:1433
    steps:
      - name: 'Check environment'
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          JOB_CONTEXT: ${{ toJson(job) }}
        run: |
          echo test
      - name: 'Setup: Wait for SQL server to be ready'
        run: |
          docker run --rm --network ${{ job.container.network }} chainguard/wait-for-it -h sqlserver -p 1433 -t 60
      - name: 'Setup: checkout'
        uses: actions/checkout@v4
      - name: 'Setup: dotnet'
        uses: actions/setup-dotnet@v4
      - name: 'Build: dotnet build'
        working-directory: ./source
        run: |
          dotnet build
